export function createChartScreenDomRefs(rootDocument: Document = document) {
  return {
    appModeBadge: rootDocument.getElementById('app-mode-badge'),
    appModeDrillLink: rootDocument.getElementById('app-mode-drill-link') as HTMLAnchorElement | null,
    appModeChartLink: rootDocument.getElementById('app-mode-chart-link') as HTMLAnchorElement | null,
    chartHomeButton: rootDocument.getElementById('chart-home-button') as HTMLAnchorElement | null,
    chartSearchInput: rootDocument.getElementById('chart-search-input') as HTMLInputElement | null,
    chartLibraryCount: rootDocument.getElementById('chart-library-count'),
    importIRealBackupButton: rootDocument.getElementById('import-ireal-backup-button') as HTMLButtonElement | null,
    openIRealForumButton: rootDocument.getElementById('open-ireal-forum-button') as HTMLButtonElement | null,
    irealLinkInput: rootDocument.getElementById('ireal-link-input') as HTMLInputElement | null,
    importIRealLinkButton: rootDocument.getElementById('import-ireal-link-button') as HTMLButtonElement | null,
    irealImportActions: rootDocument.getElementById('chart-import-native-actions'),
    irealLinkImportSection: rootDocument.getElementById('ireal-link-import-section'),
    chartImportStatus: rootDocument.getElementById('chart-import-status'),
    irealBackupInput: rootDocument.getElementById('ireal-backup-input') as HTMLInputElement | null,
    fixtureSelect: rootDocument.getElementById('fixture-select') as HTMLSelectElement | null,
    transposeSelect: rootDocument.getElementById('transpose-select') as HTMLSelectElement | null,
    harmonyDisplayMode: rootDocument.getElementById('harmony-display-mode') as HTMLSelectElement | null,
    useChordSymbolV2: rootDocument.getElementById('use-chord-symbol-v2') as HTMLInputElement | null,
    useMajorTriangleSymbol: rootDocument.getElementById('use-major-triangle-symbol') as HTMLInputElement | null,
    useHalfDiminishedSymbol: rootDocument.getElementById('use-half-diminished-symbol') as HTMLInputElement | null,
    useDiminishedSymbol: rootDocument.getElementById('use-diminished-symbol') as HTMLInputElement | null,
    tempoInput: rootDocument.getElementById('tempo-input') as HTMLInputElement | null,
    tempoButton: rootDocument.getElementById('tempo-button') as HTMLButtonElement | null,
    tempoButtonLabel: rootDocument.getElementById('tempo-button-label'),
    tempoPopover: rootDocument.getElementById('tempo-popover'),
    tempoPopoverValue: rootDocument.getElementById('tempo-popover-value'),
    tempoRange: rootDocument.getElementById('tempo-range') as HTMLInputElement | null,
    mixerButton: rootDocument.getElementById('chart-mixer-button') as HTMLButtonElement | null,
    mixerPopover: rootDocument.getElementById('mixer-popover'),
    sheetStyle: rootDocument.getElementById('sheet-style'),
    sheetTitle: rootDocument.getElementById('sheet-title'),
    sheetSubtitle: rootDocument.getElementById('sheet-subtitle'),
    sheetTimeSignature: rootDocument.getElementById('sheet-time-signature'),
    sheetKey: rootDocument.getElementById('sheet-key'),
    previousChartButton: rootDocument.getElementById('previous-chart-button') as HTMLButtonElement | null,
    nextChartButton: rootDocument.getElementById('next-chart-button') as HTMLButtonElement | null,
    sheetGrid: rootDocument.getElementById('sheet-grid'),
    chartMeta: rootDocument.getElementById('chart-meta'),
    diagnosticsList: rootDocument.getElementById('diagnostics-list'),
    transportStatus: rootDocument.getElementById('transport-status'),
    transportPosition: rootDocument.getElementById('transport-position'),
    playButton: rootDocument.getElementById('play-button') as HTMLButtonElement | null,
    stopButton: rootDocument.getElementById('stop-button') as HTMLButtonElement | null,
    compingStyleSelect: rootDocument.getElementById('comping-style-select') as HTMLSelectElement | null,
    drumsSelect: rootDocument.getElementById('drums-select') as HTMLSelectElement | null,
    walkingBassToggle: rootDocument.getElementById('walking-bass-toggle') as HTMLInputElement | null,
    masterVolume: rootDocument.getElementById('master-volume') as HTMLInputElement | null,
    masterVolumeValue: rootDocument.getElementById('master-volume-value'),
    bassVolume: rootDocument.getElementById('bass-volume') as HTMLInputElement | null,
    bassVolumeValue: rootDocument.getElementById('bass-volume-value'),
    stringsVolume: rootDocument.getElementById('strings-volume') as HTMLInputElement | null,
    stringsVolumeValue: rootDocument.getElementById('strings-volume-value'),
    drumsVolume: rootDocument.getElementById('drums-volume') as HTMLInputElement | null,
    drumsVolumeValue: rootDocument.getElementById('drums-volume-value'),
    playbackBridgeFrame: rootDocument.getElementById('playback-bridge-frame') as HTMLIFrameElement | null,
    selectionSummary: rootDocument.getElementById('selection-summary'),
    clearSelectionButton: rootDocument.getElementById('clear-selection-button') as HTMLButtonElement | null,
    sendSelectionToPracticeButton: rootDocument.getElementById('send-selection-to-practice-button') as HTMLButtonElement | null,
    selectionMenu: rootDocument.getElementById('chart-selection-menu'),
    selectionLoopButton: rootDocument.getElementById('selection-loop-button') as HTMLButtonElement | null,
    selectionCreateDrillButton: rootDocument.getElementById('selection-create-drill-button') as HTMLButtonElement | null,
    mobileMenuToggle: rootDocument.getElementById('mobile-menu-toggle') as HTMLButtonElement | null,
    mobileBackdrop: rootDocument.getElementById('chart-mobile-backdrop'),
    chartMetadataButton: rootDocument.getElementById('chart-metadata-button') as HTMLButtonElement | null,
    chartMetadataPopover: rootDocument.getElementById('chart-metadata-popover'),
    manageChartsButton: rootDocument.getElementById('manage-charts-button') as HTMLButtonElement | null,
    manageChartsPopover: rootDocument.getElementById('manage-charts-popover'),
    instrumentSettingsButton: rootDocument.getElementById('instrument-settings-button') as HTMLButtonElement | null,
    instrumentSettingsPopover: rootDocument.getElementById('instrument-settings-popover'),
    instrumentTransposeSelect: rootDocument.getElementById('instrument-transpose-select') as HTMLSelectElement | null,
    exportChartPdfButton: rootDocument.getElementById('export-chart-pdf-button') as HTMLButtonElement | null,
    chartTopOverlay: rootDocument.getElementById('chart-top-overlay'),
    chartBottomOverlay: rootDocument.getElementById('chart-bottom-overlay'),
    chartApp: rootDocument.querySelector<HTMLElement>('.chart-app')
  };
}
