export function createDrillDomRefs(documentRef: Document = document) {
  return {
    appVersion: documentRef.getElementById('app-version'),
    display: documentRef.getElementById('display'),
    selectedKeysSummary: documentRef.getElementById('selected-keys-summary'),
    displayPlaceholder: documentRef.getElementById('display-placeholder'),
    displayPlaceholderMessage: documentRef.getElementById('display-placeholder-message'),
    keyDisplay: documentRef.getElementById('key-display'),
    chordDisplay: documentRef.getElementById('chord-display'),
    nextHeader: documentRef.getElementById('next-header'),
    nextKeyDisplay: documentRef.getElementById('next-key-display'),
    nextChordDisplay: documentRef.getElementById('next-chord-display'),
    compingStyle: documentRef.getElementById('comping-style'),
    drumsSelect: documentRef.getElementById('drums-select'),
    patternHelp: documentRef.getElementById('pattern-help'),
    patternPicker: documentRef.getElementById('pattern-picker'),
    patternSelect: documentRef.getElementById('pattern-select') as HTMLSelectElement | null,
    patternPickerCustom: documentRef.getElementById('pattern-picker-custom'),
    patternPreview: documentRef.getElementById('pattern-preview'),
    patternPreviewRow: documentRef.querySelector('.pattern-preview-row'),
    patternPreviewDefaultAnchor: documentRef.getElementById('pattern-preview-default-anchor'),
    patternPreviewEditAnchor: documentRef.getElementById('pattern-preview-edit-anchor'),
    customPatternPanel: documentRef.getElementById('custom-pattern-panel'),
    customPattern: documentRef.getElementById('custom-pattern') as HTMLTextAreaElement | HTMLInputElement | null,
    patternName: documentRef.getElementById('pattern-name') as HTMLInputElement | null,
    patternMode: documentRef.getElementById('pattern-mode') as HTMLSelectElement | null,
    patternModeBoth: documentRef.getElementById('pattern-mode-both') as HTMLInputElement | null,
    patternError: documentRef.getElementById('pattern-error'),
    saveProgression: documentRef.getElementById('save-progression'),
    cancelProgressionEdit: documentRef.getElementById('cancel-progression-edit'),
    newProgression: documentRef.getElementById('new-progression'),
    editProgression: documentRef.getElementById('edit-progression'),
    deleteProgression: documentRef.getElementById('delete-progression'),
    manageProgressions: documentRef.getElementById('manage-progressions'),
    progressionManagerPanel: documentRef.getElementById('progression-manager-panel'),
    progressionManagerList: documentRef.getElementById('progression-manager-list'),
    closeProgressionManager: documentRef.getElementById('close-progression-manager'),
    restoreDefaultProgressions: documentRef.getElementById('restore-default-progressions'),
    clearAllProgressions: documentRef.getElementById('clear-all-progressions'),
    progressionFeedback: documentRef.getElementById('progression-feedback'),
    progressionUpdateModal: documentRef.getElementById('progression-update-modal'),
    progressionUpdateMessage: documentRef.getElementById('progression-update-message'),
    progressionUpdateReplace: documentRef.getElementById('progression-update-replace'),
    progressionUpdateMerge: documentRef.getElementById('progression-update-merge'),
    progressionUpdateKeep: documentRef.getElementById('progression-update-keep'),
    tempoSlider: documentRef.getElementById('tempo-slider') as HTMLInputElement | null,
    tempoValue: documentRef.getElementById('tempo-value'),
    repetitionsPerKey: documentRef.getElementById('repetitions-per-key') as HTMLInputElement | HTMLSelectElement | null,
    transpositionSelect: documentRef.getElementById('transposition-select') as HTMLSelectElement | null,
    nextPreviewValue: documentRef.getElementById('next-preview-value') as HTMLInputElement | null,
    nextPreviewUnitToggle: documentRef.getElementById('next-preview-unit-toggle') as HTMLInputElement | null,
    nextPreviewHint: documentRef.getElementById('next-preview-hint'),
    chordsPerBar: documentRef.getElementById('chords-per-bar') as HTMLSelectElement | null,
    doubleTimeRow: documentRef.getElementById('double-time-row'),
    doubleTimeToggle: documentRef.getElementById('double-time') as HTMLInputElement | null,
    majorMinor: documentRef.getElementById('major-minor') as HTMLInputElement | null,
    displayMode: documentRef.getElementById('display-mode') as HTMLSelectElement | null,
    harmonyDisplayMode: documentRef.getElementById('harmony-display-mode') as HTMLSelectElement | null,
    useMajorTriangleSymbol: documentRef.getElementById('use-major-triangle-symbol') as HTMLInputElement | null,
    useHalfDiminishedSymbol: documentRef.getElementById('use-half-diminished-symbol') as HTMLInputElement | null,
    useDiminishedSymbol: documentRef.getElementById('use-diminished-symbol') as HTMLInputElement | null,
    debugToggle: documentRef.getElementById('debug-toggle') as HTMLInputElement | null,
    keyPicker: documentRef.getElementById('key-picker') as HTMLDetailsElement | null,
    keyPickerBackdrop: documentRef.getElementById('key-picker-backdrop'),
    closeKeyPicker: documentRef.getElementById('close-key-picker'),
    startStop: documentRef.getElementById('start-stop'),
    pause: documentRef.getElementById('pause'),
    beatIndicator: documentRef.getElementById('beat-indicator'),
    beatDots: documentRef.querySelectorAll('.beat-dot'),
    selectAllKeys: documentRef.getElementById('select-all-keys'),
    invertKeys: documentRef.getElementById('invert-keys'),
    clearAllKeys: documentRef.getElementById('clear-all-keys'),
    saveKeyPreset: documentRef.getElementById('save-key-preset'),
    loadKeyPreset: documentRef.getElementById('load-key-preset'),
    keyCheckboxes: documentRef.getElementById('key-checkboxes'),
    masterVolume: documentRef.getElementById('master-volume'),
    masterVolumeValue: documentRef.getElementById('master-volume-value'),
    bassVolume: documentRef.getElementById('bass-volume'),
    bassVolumeValue: documentRef.getElementById('bass-volume-value'),
    stringsVolume: documentRef.getElementById('strings-volume'),
    stringsVolumeValue: documentRef.getElementById('strings-volume-value'),
    drumsVolume: documentRef.getElementById('drums-volume'),
    drumsVolumeValue: documentRef.getElementById('drums-volume-value'),
    walkingBass: documentRef.getElementById('walking-bass-toggle') as HTMLInputElement | null,
    showBeatIndicator: documentRef.getElementById('show-beat-indicator') as HTMLInputElement | null,
    hideCurrentHarmony: documentRef.getElementById('hide-current-harmony') as HTMLInputElement | null,
    welcomeOverlay: documentRef.getElementById('welcome-overlay'),
    welcomeSkip: documentRef.getElementById('welcome-skip'),
    welcomeApply: documentRef.getElementById('welcome-apply'),
    welcomeSummary: documentRef.getElementById('welcome-summary'),
    welcomeGoalPanels: documentRef.querySelectorAll('[data-welcome-panel]'),
    reopenWelcome: documentRef.getElementById('reopen-welcome'),
    welcomeStandardSelect: documentRef.getElementById('welcome-standard-select'),
    welcomeShowNextTime: documentRef.getElementById('welcome-show-next-time'),
    resetSettings: documentRef.getElementById('reset-settings'),
    pianoToolsPanel: documentRef.getElementById('piano-tools-panel'),
    pianoMidiEnabled: documentRef.getElementById('piano-midi-enabled'),
    pianoMidiStatus: documentRef.getElementById('piano-midi-status'),
    pianoMidiInput: documentRef.getElementById('piano-midi-input'),
    pianoMidiRefresh: documentRef.getElementById('piano-midi-refresh'),
    pianoMidiSustain: documentRef.getElementById('piano-midi-sustain'),
    pianoTimeConstantLow: documentRef.getElementById('piano-time-constant-low'),
    pianoTimeConstantHigh: documentRef.getElementById('piano-time-constant-high'),
    pianoSettingsJson: documentRef.getElementById('piano-settings-json'),
    pianoSettingsCopy: documentRef.getElementById('piano-settings-copy'),
    pianoSettingsApply: documentRef.getElementById('piano-settings-apply'),
    pianoSettingsReset: documentRef.getElementById('piano-settings-reset')
  };
}
