
type PracticePlaybackHelperBindings = Record<string, unknown>;

export function createPracticePlaybackSchedulerHelpers(helpers: PracticePlaybackHelperBindings = {}) {
  return {
    applyDisplaySideLayout: helpers.applyDisplaySideLayout,
    buildPreparedBassPlan: helpers.buildPreparedBassPlan,
    buildLegacyVoicingPlan: helpers.buildLegacyVoicingPlan,
    buildLoopRepVoicings: helpers.buildLoopRepVoicings,
    buildPreparedCompingPlans: helpers.buildPreparedCompingPlans,
    buildVoicingPlanForSlots: helpers.buildVoicingPlanForSlots,
    bassMidiToNoteName: helpers.bassMidiToNoteName,
    canLoopTrimProgression: helpers.canLoopTrimProgression,
    chordSymbolHtml: helpers.chordSymbolHtml,
    chordSymbol: helpers.chordSymbol,
    compingEngine: helpers.compingEngine,
    createOneChordToken: helpers.createOneChordToken,
    createVoicingSlot: helpers.createVoicingSlot,
    fitHarmonyDisplay: helpers.fitHarmonyDisplay,
    getBassMidi: helpers.getBassMidi,
    getBeatsPerChord: helpers.getBeatsPerChord,
    getChordsPerBar: helpers.getChordsPerBar,
    getPlaybackMeasurePlan: helpers.getPlaybackMeasurePlan,
    getMeasureInfoForChordIndex: helpers.getMeasureInfoForChordIndex,
    getCompingStyle: helpers.getCompingStyle,
    getCurrentPatternString: helpers.getCurrentPatternString,
    getPatternKeyOverridePitchClass: helpers.getPatternKeyOverridePitchClass,
    isWalkingBassDebugEnabled: helpers.isWalkingBassDebugEnabled,
    getRemainingBeatsUntilNextProgression: helpers.getRemainingBeatsUntilNextProgression,
    getRepetitionsPerKey: helpers.getRepetitionsPerKey,
    getFinitePlayback: helpers.getFinitePlayback,
    getPlaybackEndingCue: helpers.getPlaybackEndingCue,
    getSecondsPerBeat: helpers.getSecondsPerBeat,
    getSwingRatio: helpers.getSwingRatio,
    hideNextCol: helpers.hideNextCol,
    ensureNearTermSamplePreload: helpers.ensureNearTermSamplePreload,
    isWalkingBassEnabled: helpers.isWalkingBassEnabled,
    isChordsEnabled: helpers.isChordsEnabled,
    isVoiceLeadingV2Enabled: helpers.isVoiceLeadingV2Enabled,
    keyName: helpers.keyName,
    nextKey: helpers.nextKey,
    padProgression: helpers.padProgression,
    parseOneChordSpec: helpers.parseOneChordSpec,
    parsePattern: helpers.parsePattern,
    playClick: helpers.playClick,
    playNote: helpers.playNote,
    playRide: helpers.playRide,
    keyNameHtml: helpers.keyNameHtml,
    renderAccidentalTextHtml: helpers.renderAccidentalTextHtml,
    scheduleDrumsForBeat: helpers.scheduleDrumsForBeat,
    shouldShowNextPreview: helpers.shouldShowNextPreview,
    showNextCol: helpers.showNextCol,
    takeNextOneChordQuality: helpers.takeNextOneChordQuality,
    trackProgressionOccurrence: helpers.trackProgressionOccurrence,
    stopPlayback: helpers.stopPlayback,
    updateBeatDots: helpers.updateBeatDots
  };
}

export function createPracticePlaybackTransportHelpers(helpers: PracticePlaybackHelperBindings = {}) {
  return {
    applyDisplaySideLayout: helpers.applyDisplaySideLayout,
    clearBeatDots: helpers.clearBeatDots,
    clearScheduledDisplays: helpers.clearScheduledDisplays,
    ensureWalkingBassGenerator: helpers.ensureWalkingBassGenerator,
    ensureNearTermSamplePreload: helpers.ensureNearTermSamplePreload,
    ensureSessionStarted: helpers.ensureSessionStarted,
    fitHarmonyDisplay: helpers.fitHarmonyDisplay,
    getPlaybackAnalyticsProps: helpers.getPlaybackAnalyticsProps,
    getProgressionAnalyticsProps: helpers.getProgressionAnalyticsProps,
    hideNextCol: helpers.hideNextCol,
    initAudio: helpers.initAudio,
    resumeAudioContext: helpers.resumeAudioContext,
    suspendAudioContext: helpers.suspendAudioContext,
    preloadStartupSamples: helpers.preloadStartupSamples,
    registerSessionAction: helpers.registerSessionAction,
    setDisplayPlaceholderMessage: helpers.setDisplayPlaceholderMessage,
    setDisplayPlaceholderVisible: helpers.setDisplayPlaceholderVisible,
    stopActiveComping: helpers.stopActiveComping,
    stopScheduledAudio: helpers.stopScheduledAudio,
    trackEvent: helpers.trackEvent,
    trackProgressionEvent: helpers.trackProgressionEvent
  };
}


