export const PLAYBACK_API_READY_EVENT = 'jpt-playback-api-ready';
export const PLAYBACK_API_GLOBAL = '__JPT_PLAYBACK_API__';
export const PLAYBACK_RUNTIME_GLOBAL = '__JPT_PLAYBACK_RUNTIME__';
export const PLAYBACK_SESSION_CONTROLLER_GLOBAL = '__JPT_PLAYBACK_SESSION_CONTROLLER__';
export const DIRECT_PLAYBACK_OPTIONS_GLOBAL = '__JPT_DIRECT_PLAYBACK_CONTROLLER_OPTIONS__';
export const DIRECT_PLAYBACK_READY_EVENT = 'jpt-direct-playback-ready';
